### ISSUE TITLE
All starflight client methods that may fail due e.g. server or network errors should allow detecting the failure

### ISSUE THREAD

**Issue by jossittelija** [StarcutFinland/StarFlight#5]
If registration or message opened request fails, user of StarflightPushClient does not know about it. This may lead apps and users thinking they have succesfully registered for push notifications when in reality are not, or unsubscribed when they still are registered. In case of message opened requests, undetected and unhandled failure leads to incorrect reporting of opened messages.

**Comment by ankushkushwaha** [comment]
Please use https://github.com/StarcutFinland/Starflight_swift from now on. It returns an error in case of request failure.
